### PR TITLE
Queue strategy top-down-level-by-level

### LINKED ISSUE #11: Queue strategy top-down-level-by-level
Problem:
Scenario 1:

Queue “ABC”, 3 Agents assigned.

Agent-A Skill priority 1.

Agent-B Skill priority 2.

Agent-C Skill priority 3.

Expected Result: Call will first go to Agent-A if no answer then Agent-B and still no answer then Agent-C.

Scenario 2:

Queue “ABC”, 3 Agents assigned.

Agent-A, Agent-B Skill priority 1.

Agent-C, Agent-D Skill priority 2.

Agent-E, Agent-F Skill priority 3.

Expected Result: Call will first go to Agent-A if no answer then Agent-B (or vice versa as priorities are the same for both) and still no answer then it will jump to priority 2 agents Agent-C and Agent-D and after that priority 3 agents.

Agent assignment at the same level will happen randomly.

P.S: Timeout and retry delay parameters will use on the agent profile to reproduce.

Conception
https://docs.google.com/document/d/1FMxmfdjARX4lv5ZPs1W_nFccpYigudO4B6-JC0Nvlv8/edit

### PR DESCRIPTION
**Pull request by surya4**
https://aswattel.atlassian.net/browse/ZIWO-5632

### CODE REVIEW

File: src/mod/applications/mod_callcenter/mod_callcenter.c [hunk 1]
```diff
@@ -2452,6 +2454,27 @@ static int agents_callback(void *pArg, int argc, char **argv, char **columnNames
...
+						if ((offered_level_agent = switch_channel_get_variable(member_channel, "cc_offered_level_agent"))) {
+							snprintf(offered_agent_list, sizeof offered_agent_list, "%s,'%s'", offered_level_agent, h->agent_name);
+						} else {
+							snprintf(offered_agent_list, sizeof offered_agent_list, "'%s'", h->agent_name);
+						}
+
+						switch_channel_set_variable(member_channel, "cc_offered_level_agent", offered_agent_list);
+						switch_channel_set_variable(member_channel, "cc_last_agent_tier_level", agent_tier_level);
+					}
+						switch_core_session_rwunlock(member_session);
```
Comment (royalpinto) [inline src/mod/applications/mod_callcenter/mod_callcenter.c:2479]: @surya4 indent back.

File: src/mod/applications/mod_callcenter/mod_callcenter.c [hunk 2]
```diff
@@ -40,6 +40,7 @@
 #define CC_SQLITE_DB_NAME "callcenter"
 #define CC_APP_KEY "mod_callcenter"
 
+#define CC_OFFERED_AGENT_LIST_SIZE 10000
```
Comment (royalpinto) [inline src/mod/applications/mod_callcenter/mod_callcenter.c]: @surya4  is it not too big?

File: src/mod/applications/mod_callcenter/mod_callcenter.c [hunk 3]
```diff
@@ -2452,6 +2454,27 @@ static int agents_callback(void *pArg, int argc, char **argv, char **columnNames
...
+					if (member_session) {
+						char offered_agent_list[CC_OFFERED_AGENT_LIST_SIZE];
+
+						switch_channel_t *member_channel = switch_core_session_get_channel(member_session);
+
+						if ((offered_level_agent = switch_channel_get_variable(member_channel, "cc_offered_level_agent"))) {
+							snprintf(offered_agent_list, sizeof offered_agent_list, "%s,'%s'", offered_level_agent, h->agent_name);
+						} else {
+							snprintf(offered_agent_list, sizeof offered_agent_list, "'%s'", h->agent_name);
+						}
```
Comment (royalpinto) [inline src/mod/applications/mod_callcenter/mod_callcenter.c]: @surya4 can it also clear the offered list if you are jumping to the next level. to optimize the list size.

Comment (royalpinto) [reply src/mod/applications/mod_callcenter/mod_callcenter.c]: check if previous and new offering level is same. if not clear and add instead of appending.

**Review by royalpinto — CHANGES_REQUESTED** [review]
Good one @surya4, minor improvements if possible to tune.

File: src/mod/applications/mod_callcenter/mod_callcenter.c (hunk 2 above)
Comment (surya4) [reply src/mod/applications/mod_callcenter/mod_callcenter.c]: done @royalpinto reduced it to 2048 now so it can handle approx 128 agents in one level, if more required we can increase list size - '000000@default' -> 1+6+1+7+1=16 characters

File: src/mod/applications/mod_callcenter/mod_callcenter.c (hunk 1 above)
Comment (surya4) [reply src/mod/applications/mod_callcenter/mod_callcenter.c:2479]: this is fine in code

File: src/mod/applications/mod_callcenter/mod_callcenter.c (hunk 3 above)
Comment (surya4) [reply src/mod/applications/mod_callcenter/mod_callcenter.c]: done @royalpinto

File: src/mod/applications/mod_callcenter/mod_callcenter.c [hunk 4]
```diff
@@ -40,6 +40,7 @@
 #define CC_SQLITE_DB_NAME "callcenter"
 #define CC_APP_KEY "mod_callcenter"
 
+#define CC_OFFERED_AGENT_LIST_SIZE 2048
```
Comment (wowi42) [inline src/mod/applications/mod_callcenter/mod_callcenter.c:43]: why 2048?

Comment (surya4) [reply src/mod/applications/mod_callcenter/mod_callcenter.c:43]: @wowi42 
this is used to maintain a string array of agent names at each level that will be used to ignore after they are offered once so, the ringing call can be offered to other available agents at this level.

example -> agents available at level 1:  cclogin1@default, cclogin2@default, cclogin3@default

say call comes and randomly offered to agent -> cclogin2@default, if he does not pick then call will go to either of the left agents and this agent will go to ignore list in below query to pick next available agent - 

query to fetch available agent -> 
`SELECT instance_id, name, status, contact, no_answer_count, max_no_answer, reject_delay_time, busy_delay_time, no_answer_delay_time, tiers.state, agents.last_bridge_end, agents.wrap_up_time, agents.state, agents.ready_time, tiers.position as tiers_position, tiers.level as tiers_level, agents.type, agents.uuid, external_calls_count, agents.last_offered_call as agents_last_offered_call FROM agents LEFT JOIN tiers ON (agents.name = tiers.agent) WHERE tiers.queue = 'abraKaDabra@default' AND (agents.status = 'Available' OR agents.status = 'On Break' OR agents.status = 'Available (On Demand)') AND tiers.level >= 2 AND name NOT IN ('0002@default') ORDER BY tiers_level ASC, random(), agents_last_offered_call`


the max an agent name can go is -> 16 characters ('000000@default')
so at each level, we can server ~110 agents in the ignore list

**Review by wowi42 — APPROVED** [review]

**Review by royalpinto — APPROVED** [review]
